version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: db
      GF_DATABASE_USER: myuser
      GF_DATABASE_PASSWORD: mypassword
      GF_DATABASE_NAME: mydatabase